Add back otel sidecar to worker-auxiliary pods (#764)
We are seeing the following errors in auxiliary pods:
```
opentelemetry.sdk.metrics._internal.export:ERROR: Exception while exporting metrics
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4318):
Max retries exceeded with url: /v1/metrics (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff9d9bf41d0>:
Failed to establish a new connection: [Errno 111] Connection refused'))
```
when a worker-auxiliary pod tries to execute some tasks like
pulpcore.app.tasks.telemetry.otel_metrics or
pulp_service.app.tasks.domain_metrics.content_sources_domains_count